import turtle
def square2(side):
        turtle.forward(50)
        turtle.left(120)
        turtle.forward(50)
        turtle.left(120)
        turtle.forward(50)
        
        turtle.left(120)
        turtle.right(90)
        turtle.forward(50)
        turtle.left(90)
        turtle.forward(20)
        turtle.left(90)
        turtle.forward(20)
        turtle.right(90)
        turtle.forward(10)
        turtle.right(90)
        turtle.forward(20)
        turtle.left(90)
        turtle.forward(20)
        turtle.left(90)
        turtle.forward(50)
        turtle.right(90)
        turtle.forward(100)
        turtle.left(120)
        turtle.forward(50)
        turtle.left(60)
        turtle.forward(100)
        turtle.left(120)
        turtle.forward(50)
        turtle.right(30)
        turtle.forward(50)
        turtle.left(90)
        turtle.forward(100)
        turtle.left(90)
        turtle.forward(50)
        
square2(50)
